# Generated by Django 5.0.7 on 2024-07-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('company_name', models.CharField(max_length=255, null=True)),
                ('registration_date', models.DateField(null=True)),
                ('registration_number', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(null=True)),
                ('contact_person', models.CharField(max_length=100, null=True)),
                ('departments', models.TextField(null=True)),
                ('number_of_employees', models.PositiveIntegerField(null=True)),
                ('contact_phone', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('employee_name', models.CharField(max_length=100, null=True)),
                ('employee_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100, null=True)),
                ('role', models.CharField(max_length=100, null=True)),
                ('date_started', models.DateField(null=True)),
                ('date_left', models.DateField(blank=True, null=True)),
                ('duties', models.TextField(null=True)),
            ],
        ),
    ]
